#!/bin/bash

# script to quantify the amount of data usage that counts against Edwards lab quota
# should be run in a location with a list of directories (e.g., user directories)
# output is a timestamp for the last time a file was accessed in each directory

for dir in `ls -d */`
do \
find ${dir} -printf "%T+\n" | sort -n | tail -1 | awk -v dir="${dir}" -v OFS="\t" '{ print dir, $1 }'; \
done
