#!/usr/bin/env bash

usage()
{
cat << EOF
compressRepMod

Version 0.1 (2020-05-13)
License: GNU GPLv2
To report bugs or errors, please contact Daren Card (daren.card@gmail.com).
This script is provided as-is, with no support and no guarantee of proper or
desirable functioning.

This script will compress the standard output of RepeatModeler, potentially saving
significant amounts of space. Based on (very limited) testing, it appears that 
compressing could result in as little as roughly 25% the disk usage of the full
output. This script can also be used to uncompress previously-compressed 
RepeatModeler output.

The user must provide the absolute or relative path to the base directory of
the RepeatModeler output. By default this is "RM_<dateinfo>" but it can also
be manually set by the user and could vary. The user may also choose to adjust
the compression level, though the default of 9 (max compression) is suggested.
The number of compression cores can also be set by the user.

Note that this script relies on pigz for multi-threaded compression, though
the default number of cores to use is 1. Ensure that pigz is installed for
proper functioning. Also note that this script will not compress any additional,
non-standard RepeatModeler output that might be present, such as that created by
the user. It is recommended that the user double check the sizes of all files 
and perform additional compression, where necessary. This script should not
modify any non-standard files/directories in the base directory.

compressRepMod -b <base_directory> -c -d [ -l <level> -t <threads> -h ]

OPTIONS:
        -h              usage information and help (this message)
        -b              base directory of the RepeatModeler output
        -c              binary flag to compress the base directory contents [false]
        -d              binary flag to decompress the base directory contents [false]
	-l		the level of compression (1-9) [9]
        -t              number of computer threads to use for compression [1]
EOF
}

THREAD=1
COMPRESS='false'
DECOMPRESS='false'
LEVEL=9

while getopts "hb:cdl:t:" OPTION
do
        case $OPTION in
                help)
                        usage
                        exit 1
                        ;;
                b)
                        BASE=$OPTARG
                        ;;
                c)
                        COMPRESS='true'
                        ;;
                d)
                        DECOMPRESS='true'
                        ;;
		l)
			LEVEL=$OPTARG
			;;
                t)
                        THREAD=$OPTARG
                        ;;
                ?)
                        usage
                        exit
                        ;;
        esac
done

if [[ -z ${BASE} ]]
then
	echo -e 'Error: base directory not provided.\n' >&2
	usage
	exit 1
fi

if [[ ${COMPRESS} == 'true' && ${DECOMPRESS} == 'true' ]]
then
	echo -e 'Error: compression and decompression both selected.\n' >&2
	usage
	exit 1
fi

if [[ ${COMPRESS} == 'false' && ${DECOMPRESS} == 'false' ]]
then
        echo -e 'Error: compression or decompression not selected.\n' >&2
        usage
        exit 1
fi

if ! [[ -x "$(command -v pigz)" ]]
then
	echo -e 'Error: pigz is not installed.\n' >&2
	usage
	exit 1
fi


if [[ ${COMPRESS} == 'true' ]]
then
	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa.classified &&
	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa &&
	pigz -${LEVEL} -p ${THREAD} ${BASE}/consensi.fa.masked &&
	if [[ -f ${BASE}/families-classified.stk ]]; then
    		pigz -${LEVEL} -p ${THREAD} ${BASE}/families-classified.stk
	fi &&
	if [[ -f ${BASE}/families.stk ]]; then
		pigz -${LEVEL} -p ${THREAD} ${BASE}/families.stk
	fi &&
	for round in `find ${BASE} -type d -name round-?`
	do
		tar cf - ${round} | pigz -${LEVEL} -p ${THREAD} > ${round}.tar.gz &&
		rm -rf ${round}
	done	
fi

if [[ ${DECOMPRESS} == 'true' ]]
then
        pigz -d -p ${THREAD} ${BASE}/consensi.fa.classified.gz &&
        pigz -d -p ${THREAD} ${BASE}/consensi.fa.gz &&
        pigz -d -p ${THREAD} ${BASE}/consensi.fa.masked.gz &&
	if [[ -f ${BASE}/families-classified.stk.gz ]]; then
        pigz -d -p ${THREAD} ${BASE}/families-classified.stk.gz
	fi &&
	if [[ -f ${BASE}/families.stk.gz ]]; then
        pigz -d -p ${THREAD} ${BASE}/families.stk.gz
	fi &&
        for round in `find ${BASE} -type f -name round-?.tar.gz`
        do
		root=`basename ${round} .tar.gz` &&
                pigz -dc -p ${THREAD} ${round} | tar xf - > ${BASE}/${root}
		rm ${round}
        done
fi
